bootstrap.servers=localhost:9092
group.id=envoy-body-events-connect

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false

offset.storage.topic=connect-offsets
config.storage.topic=connect-configs
status.storage.topic=connect-status
offset.storage.replication.factor=1
config.storage.replication.factor=1
status.storage.replication.factor=1

plugin.path=/root/confluent-7.6.0/share/java/
listeners=HTTP://0.0.0.0:18083
rest.advertised.host.name=localhost
rest.advertised.port=18083


